<a href="https://colab.research.google.com/github/shivakumarsanugula/Kaggle-NLP/blob/main/Word_embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.14.0


In [4]:
# one-hot
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
#cocabulary size
voc_size = 10000

One Hot Representation

In [8]:
onehot_repr = [one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[359, 90, 5946, 8515], [359, 90, 5946, 3300], [359, 4313, 5946, 2557], [2153, 701, 968, 9634, 4475], [2153, 701, 968, 9634, 2357], [1756, 359, 3420, 5946, 7324], [8528, 1838, 6497, 9634]]


Word Embedding Representation

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [11]:
## pre padding
sent_length = 8
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  359   90 5946 8515]
 [   0    0    0    0  359   90 5946 3300]
 [   0    0    0    0  359 4313 5946 2557]
 [   0    0    0 2153  701  968 9634 4475]
 [   0    0    0 2153  701  968 9634 2357]
 [   0    0    0 1756  359 3420 5946 7324]
 [   0    0    0    0 8528 1838 6497 9634]]


In [12]:
# convert each and every value into vectors
dim = 10 #feature representation dimension

In [13]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 108ms/step


array([[ 2.1035101e-02, -3.8082231e-02, -3.2806970e-02, -1.2489270e-02,
        -9.8806396e-03, -4.6084788e-02,  3.4970526e-02,  2.9962063e-03,
        -3.1485200e-02,  1.7477963e-02],
       [ 2.1035101e-02, -3.8082231e-02, -3.2806970e-02, -1.2489270e-02,
        -9.8806396e-03, -4.6084788e-02,  3.4970526e-02,  2.9962063e-03,
        -3.1485200e-02,  1.7477963e-02],
       [ 2.1035101e-02, -3.8082231e-02, -3.2806970e-02, -1.2489270e-02,
        -9.8806396e-03, -4.6084788e-02,  3.4970526e-02,  2.9962063e-03,
        -3.1485200e-02,  1.7477963e-02],
       [ 2.1035101e-02, -3.8082231e-02, -3.2806970e-02, -1.2489270e-02,
        -9.8806396e-03, -4.6084788e-02,  3.4970526e-02,  2.9962063e-03,
        -3.1485200e-02,  1.7477963e-02],
       [ 7.0531592e-03, -3.7719630e-02,  1.3655674e-02,  2.8936196e-02,
         1.8134836e-02,  3.3058587e-02,  9.4221123e-03,  2.5435176e-02,
        -2.2484267e-02, -4.3430008e-02],
       [ 3.1905938e-02,  2.6972305e-02, -4.2203724e-02, -2.6572669e-02,
   

In [16]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 42ms/step
[[[ 2.1035101e-02 -3.8082231e-02 -3.2806970e-02 -1.2489270e-02
   -9.8806396e-03 -4.6084788e-02  3.4970526e-02  2.9962063e-03
   -3.1485200e-02  1.7477963e-02]
  [ 2.1035101e-02 -3.8082231e-02 -3.2806970e-02 -1.2489270e-02
   -9.8806396e-03 -4.6084788e-02  3.4970526e-02  2.9962063e-03
   -3.1485200e-02  1.7477963e-02]
  [ 2.1035101e-02 -3.8082231e-02 -3.2806970e-02 -1.2489270e-02
   -9.8806396e-03 -4.6084788e-02  3.4970526e-02  2.9962063e-03
   -3.1485200e-02  1.7477963e-02]
  [ 2.1035101e-02 -3.8082231e-02 -3.2806970e-02 -1.2489270e-02
   -9.8806396e-03 -4.6084788e-02  3.4970526e-02  2.9962063e-03
   -3.1485200e-02  1.7477963e-02]
  [ 7.0531592e-03 -3.7719630e-02  1.3655674e-02  2.8936196e-02
    1.8134836e-02  3.3058587e-02  9.4221123e-03  2.5435176e-02
   -2.2484267e-02 -4.3430008e-02]
  [ 3.1905938e-02  2.6972305e-02 -4.2203724e-02 -2.6572669e-02
    2.1212582e-02 -1.2646258e-02  7.2609633e-05  9.1650374e-03
    2.6003543e-02 -3.9